apiVersion: v1
kind: Service
metadata:
  name: despacho-backend
  namespace: innovatech-despachos
spec:
  selector:
    app: despacho-backend
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
